    FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    RUN sudo apt update && sudo apt install && \
        sudo npm upgrade -g pnpm && \
        sudo apt-get install -y cpio inotify-tools